apiVersion: apps/v1
kind: Deployment
metadata:   
  annotations:  
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas" 
  name: go-cmfhiekk
spec:
  replicas: 1 
  template: 
    spec:
      containers:
      - image: quay.io/rhtap_qe/go-cmfhiekk:4f3045dac62a357fc754cbb4e978af5f8280f4e4@sha256:24994b7620ab02a88c3b4ee15de09380e01005768db8155da270f52d86ba63f3
        name: container-image  
